version: "3.9"

services:
  mrivals-front:
    build: .
    container_name: mrivals-front
    restart: always

    labels:
      - "traefik.enable=true"

      # ROUTEUR FRONT HTTPS
      - "traefik.http.routers.mrivals-front.rule=Host(`mrivals-builder.com`, `www.mrivals-builder.com`)"
      - "traefik.http.routers.mrivals-front.entrypoints=websecure"
      - "traefik.http.routers.mrivals-front.tls.certresolver=le"

      # SERVICE (port interne du container)
      - "traefik.http.services.mrivals-front.loadbalancer.server.port=80"

    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
    name: traefik_traefik-network
